#define LOG_CONF_LEVEL_DEFAULT LOG_LEVEL_DBG

#define LOG_CONF_LEVEL_FILE LOG_CONF_LEVEL_DEFAULT
#define LOG_CONF_LEVEL_CONNECTION LOG_CONF_LEVEL_DEFAULT
#define LOG_CONF_LEVEL_MESSAGE LOG_CONF_LEVEL_DEFAULT

#define PACKETBUF_CONF_SIZE               1280
