#define LOG_CONF_LEVEL_DEFAULT LOG_LEVEL_DBG

#define LOG_CONF_LEVEL_FILE LOG_CONF_LEVEL_DEFAULT
#define LOG_CONF_LEVEL_CONNECTION LOG_CONF_LEVEL_DEFAULT
#define LOG_CONF_LEVEL_MESSAGE LOG_CONF_LEVEL_DEFAULT

#define RF_CONF_RX_BUF_SIZE 256
#define PACKETBUF_CONF_SIZE 256
#define UIP_CONF_BUFFER_SIZE 256
#define SICSLOWPAN_CONF_MAC_MAX_PAYLOAD 256
#define QUEUEBUF_CONF_NUM 1
