CONTIKI_PROJECT = Producer
all: $(CONTIKI_PROJECT)


PROJECTDIRS += ../Shared/File
PROJECTDIRS += ../Shared/Types
PROJECTDIRS += ../Images/Lena

PROJECT_SOURCEFILES += file.c
PROJECT_SOURCEFILES += lena1.c

CONTIKI = ../..

include $(CONTIKI)/Makefile.include
